# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Client-side driver for NeMo StreamingSTT decoding over a vLLM session.

Wraps vLLM's resumable streaming-session API (one ``StreamingInput`` per audio
chunk turn) into a reusable :class:`StreamingSTTSession`. For each chunk the
session sends ``<user header> <audio> <assistant header>`` with one audio item
carrying that chunk's precomputed embeddings (see :func:`stream_encode`), lets
the LLM decode until a stop blank / EOS, and -- together with the
``register()``-installed scheduler patch -- carries the chunk's text + blank +
footer into the next chunk's KV. Generated token streams are decoded to text by
splitting on the blank (segment) token, mirroring NeMo's ``decode_with_blank``.

The chunk-boundary marker token IDs and turn-template token IDs are carried in a
:class:`StreamingMarkers`, which can be built from a markers dict / JSON file or
from the model's HF config.

Turn-Taking Manager (TTM) checkpoints additionally declare ``sou_id`` /
``eou_id`` in their markers. When that pair is present the session observes the
boundary tokens in the raw DELTA stream (before transcript cleanup), reports
them as :class:`StreamingBoundaryEvent`\\ s, and -- by default -- closes the
request and resets vLLM's multimodal cache at the first EOU. Checkpoints
without the pair keep the transcript-only blank/EOS behavior unchanged.
"""

import asyncio
import inspect
import re
from dataclasses import dataclass, replace
from typing import Any, Awaitable, Callable, Literal

# The opt-in extra_args contract keys live in a shared, dependency-free module so
# the producer (this file) and the consumer (streaming_scheduler) cannot drift.
from nemo.collections.speechlm2.vllm.salm.streaming_constants import (
    BLANK_ID_KEY,
    EOS_ID_KEY,
    FOOTER_IDS_KEY,
    RETAIN_FLAG,
)


@dataclass(frozen=True)
class StreamingBoundaryEvent:
    """One SOU/EOU token observed in the raw vLLM DELTA stream.

    Attributes:
        boundary_type: ``"sou"`` (start of utterance) or ``"eou"`` (end of it).
        token_id: The marker token ID as generated by the model.
        token_index: Position of the token in the session's flat token stream.
        chunk_index: Index of the audio chunk the token was generated for.
        chunk_end_audio_seconds: Audio time at the end of that chunk.
    """

    boundary_type: Literal["sou", "eou"]
    token_id: int
    token_index: int
    chunk_index: int
    chunk_end_audio_seconds: float


@dataclass(frozen=True)
class StreamingTranscriptionResult:
    """Transcript plus raw tokens, turn boundaries, and EOU cleanup state."""

    text: str
    token_ids: list[int]
    boundary_events: list[StreamingBoundaryEvent]
    ended_by_eou: bool
    request_aborted: bool
    mm_cache_reset: bool


@dataclass
class _SessionRunResult:
    """Internal per-session run state handed to the transcript decoder."""

    token_ids: list[int]
    boundary_events: list[StreamingBoundaryEvent]
    ended_by_eou: bool = False
    request_aborted: bool = False
    mm_cache_reset: bool = False


BoundaryCallback = Callable[[StreamingBoundaryEvent], Awaitable[None] | None]


@dataclass
class StreamingMarkers:
    """Token IDs and turn-template pieces that define a StreamingSTT turn.

    Attributes:
        chunk_size: Encoder output frames per chunk (audio placeholders expand to
            this count).
        blank_token_id: The ``<blank>`` segment-boundary token.
        eos_id: End-of-turn token (e.g. ``<|im_end|>``).
        audio_id: The audio locator token a chunk's embeddings replace.
        asst_footer_ids: Assistant turn footer (e.g. ``[<|im_end|>, \\n]``).
        user_header_ids: User turn header (e.g. ``[<|im_start|>, user, \\n]``).
        uf_ah_ids: User-footer + assistant-header tokens that follow the audio.
        system_prompt: System prompt rendered (via chat template) on chunk 0.
        has_blank: Whether the checkpoint uses a dedicated blank token.
        sou_id: Optional start-of-utterance token (TTM checkpoints only).
        eou_id: Optional end-of-utterance token (TTM checkpoints only).
        frame_length_seconds: Audio seconds per encoder output frame; used to
            stamp boundary events with their chunk-end audio time.

    ``sou_id`` and ``eou_id`` are optional but must be given as a pair. Their
    absence selects the transcript-only behavior; their presence enables raw
    boundary observation and EOU request cleanup.
    """

    chunk_size: int
    blank_token_id: int
    eos_id: int
    audio_id: int
    asst_footer_ids: list[int]
    user_header_ids: list[int]
    uf_ah_ids: list[int]
    system_prompt: str = "Transcribe the audio into text."
    has_blank: bool = True
    sou_id: int | None = None
    eou_id: int | None = None
    frame_length_seconds: float = 0.08

    def __post_init__(self) -> None:
        if (self.sou_id is None) != (self.eou_id is None):
            raise ValueError("sou_id and eou_id must either both be set or both be omitted")
        if self.frame_length_seconds <= 0:
            raise ValueError("frame_length_seconds must be positive")
        if self.sou_id is not None:
            # For noblank checkpoints blank_token_id is the ``-1`` sentinel, not a
            # real vocab id, so it is excluded from the collision check.
            special_ids = {
                "blank_token_id": self.blank_token_id if self.has_blank else None,
                "eos_id": self.eos_id,
                "audio_id": self.audio_id,
                "sou_id": self.sou_id,
                "eou_id": self.eou_id,
            }
            values = [value for value in special_ids.values() if value is not None]
            if len(values) != len(set(values)):
                raise ValueError(f"streaming marker IDs must be distinct: {special_ids}")

    @property
    def has_boundaries(self) -> bool:
        """Whether this checkpoint declares the SOU/EOU turn-boundary pair."""
        return self.sou_id is not None and self.eou_id is not None

    @classmethod
    def from_dict(cls, data: dict) -> "StreamingMarkers":
        """Build markers from a markers dict (e.g. loaded from ``markers.json``).

        ``sou_id`` / ``eou_id`` may sit at the top level or inside a nested
        ``boundary_markers`` sub-dict.
        """
        boundary_data = data.get("boundary_markers") or {}

        def optional_int(name: str) -> int | None:
            value = data.get(name, boundary_data.get(name))
            return None if value is None else int(value)

        return cls(
            chunk_size=int(data["chunk_size"]),
            blank_token_id=int(data["blank_token_id"]),
            eos_id=int(data["eos_id"]),
            audio_id=int(data.get("audio_id", 151670)),
            asst_footer_ids=list(data["asst_footer_ids"]),
            user_header_ids=list(data["user_header_ids"]),
            uf_ah_ids=list(data["uf_ah_ids"]),
            system_prompt=data.get("system_prompt", "Transcribe the audio into text."),
            has_blank=bool(data.get("has_blank", True)),
            sou_id=optional_int("sou_id"),
            eou_id=optional_int("eou_id"),
            frame_length_seconds=float(data.get("frame_length_seconds", 0.08)),
        )

    @classmethod
    def from_config(cls, hf_config: Any) -> "StreamingMarkers":
        """Build markers from a model's HF config ``streaming_markers`` field.

        Lets a checkpoint be self-describing (no external markers file). Raises if
        the config does not carry ``streaming_markers``.
        """
        data = getattr(hf_config, "streaming_markers", None)
        if not data:
            raise ValueError(
                "Model config has no 'streaming_markers'; export the checkpoint with "
                "streaming markers or pass an explicit markers dict via from_dict()."
            )
        return cls.from_dict(data)


class StreamingSTTSession:
    """Decode StreamingSTT utterances over vLLM resumable streaming sessions.

    One :class:`StreamingSTTSession` is reused across utterances; each call to
    :meth:`transcribe` opens an independent vLLM session (its own ``request_id``
    and KV cache) and feeds the utterance's per-chunk embeddings one chunk turn
    at a time.

    Args:
        engine: A vLLM ``AsyncLLM`` built with ``enable_mm_embeds=True`` and (for
            the resumable session API) ``async_scheduling=False``.
        tokenizer: HF tokenizer for the model (used for the chunk-0 system-prompt
            chat-template render and for detokenizing output segments).
        markers: Token IDs / turn-template pieces (:class:`StreamingMarkers`).
        max_tokens: Per-chunk ``max_tokens`` (NeMo uses 64 per chunk turn).
        close_on_eou: Abort the active request at the first EOU token (TTM
            checkpoints only). Disable for observe-only boundary reporting.
        reset_mm_cache_on_eou: Reset the engine's multimodal cache after the EOU
            abort.
    """

    def __init__(
        self,
        engine: Any,
        tokenizer: Any,
        markers: StreamingMarkers,
        *,
        max_tokens: int = 64,
        close_on_eou: bool = True,
        reset_mm_cache_on_eou: bool = True,
    ):
        from vllm import SamplingParams
        from vllm.sampling_params import RequestOutputKind

        self.engine = engine
        self.tokenizer = tokenizer
        self.markers = markers
        self.close_on_eou = bool(close_on_eou)
        self.reset_mm_cache_on_eou = bool(reset_mm_cache_on_eou)

        self.sys_ids = tokenizer.apply_chat_template(
            [{"role": "system", "content": markers.system_prompt}],
            tokenize=True,
            add_generation_prompt=False,
            enable_thinking=False,
        )
        # One audio placeholder per chunk: the SALM multimodal processor expands
        # it to the embedding frame count. Emitting chunk_size literal locators
        # instead double-expands and corrupts the audio context.
        self.audio_ph = [markers.audio_id]

        # For noblank checkpoints (``has_blank=False``) ``blank_token_id`` is the
        # ``-1`` sentinel -- a comparison marker, never a real vocab id. Only feed
        # it as a stop token / KV filler when the checkpoint has a real blank
        # token; otherwise chunks segment on EOS alone. Feeding ``-1`` would index
        # the embedding table at -1 and trip a CUDA gather out-of-bounds assert.
        extra_args = {
            RETAIN_FLAG: True,
            EOS_ID_KEY: markers.eos_id,
            FOOTER_IDS_KEY: list(markers.asst_footer_ids),
        }
        stop_token_ids = [markers.eos_id]
        if markers.has_blank:
            extra_args[BLANK_ID_KEY] = markers.blank_token_id
            stop_token_ids = [markers.blank_token_id, markers.eos_id]
        # EOU is deliberately not a vLLM stop token: it must stay visible in the
        # RequestOutputKind.DELTA stream so the boundary consumer can observe it.
        self._chunk_sp = SamplingParams(
            temperature=0.0,
            max_tokens=max_tokens,
            stop_token_ids=stop_token_ids,
            output_kind=RequestOutputKind.DELTA,
            extra_args=extra_args,
        )

    def _chunk_wrapper(self, chunk_index: int) -> list[int]:
        """Per-chunk turn token IDs: (system on chunk 0) + user header + audio + asst header."""
        prefix = list(self.sys_ids) if chunk_index == 0 else []
        return prefix + self.markers.user_header_ids + self.audio_ph + self.markers.uf_ah_ids

    def _stream_input(self, chunks: list[Any], chunk_index: int) -> Any:
        """One ``StreamingInput`` turn carrying chunk ``chunk_index``'s embeddings."""
        from vllm.engine.protocol import StreamingInput
        from vllm.inputs import TokensPrompt

        return StreamingInput(
            prompt=TokensPrompt(
                prompt_token_ids=self._chunk_wrapper(chunk_index),
                multi_modal_data={"audio": [chunks[chunk_index]]},
            ),
            sampling_params=self._chunk_sp,
        )

    async def _run_session_transcript_only(self, chunks: list[Any], request_id: str, throttle: bool) -> list[int]:
        """Run one utterance's streaming session; return the flat generated token IDs.

        This is the boundary-free path taken by checkpoints without SOU/EOU: no
        raw-stream observation, no request abort, no multimodal cache reset.
        """
        blank_id, eos_id = self.markers.blank_token_id, self.markers.eos_id

        if throttle:
            # One chunk in flight, gated on its output -- useful for debugging /
            # strict per-chunk inspection.
            done: asyncio.Queue = asyncio.Queue()

            async def gen_throttled():
                for i in range(len(chunks)):
                    yield self._stream_input(chunks, i)
                    await done.get()

            per_chunk: list[list[int]] = []
            cur: list[int] = []
            async for out in self.engine.generate(gen_throttled(), self._chunk_sp, request_id=request_id):
                d = out.outputs[0]
                cur.extend(list(d.token_ids))
                if d.finish_reason is not None or (cur and cur[-1] in (blank_id, eos_id)):
                    per_chunk.append(cur)
                    cur = []
                    await done.put(1)
                if len(per_chunk) >= len(chunks):
                    break
            return [t for group in per_chunk for t in group]

        # Throughput mode: eager-yield all chunk turns; the engine queues and
        # advances the session internally. Drain to the end.
        async def gen_throughput():
            for i in range(len(chunks)):
                yield self._stream_input(chunks, i)

        flat: list[int] = []
        async for out in self.engine.generate(gen_throughput(), self._chunk_sp, request_id=request_id):
            flat.extend(list(out.outputs[0].token_ids))
            if out.finished:
                break
        return flat

    async def _emit_boundary_events(
        self,
        token_ids: list[int],
        *,
        token_offset: int,
        chunk_index: int,
        on_boundary: BoundaryCallback | None,
    ) -> tuple[list[StreamingBoundaryEvent], int]:
        """Collect SOU/EOU events in one DELTA and advance the chunk counter."""
        if not self.markers.has_boundaries:
            return [], chunk_index
        events: list[StreamingBoundaryEvent] = []
        boundary_ids = {self.markers.sou_id: "sou", self.markers.eou_id: "eou"}
        chunk_end_ids = {self.markers.eos_id}
        if self.markers.has_blank:
            chunk_end_ids.add(self.markers.blank_token_id)
        for offset, token_id in enumerate(token_ids):
            boundary_type = boundary_ids.get(token_id)
            if boundary_type is not None:
                event = StreamingBoundaryEvent(
                    boundary_type=boundary_type,
                    token_id=token_id,
                    token_index=token_offset + offset,
                    chunk_index=chunk_index,
                    chunk_end_audio_seconds=(chunk_index + 1)
                    * self.markers.chunk_size
                    * self.markers.frame_length_seconds,
                )
                events.append(event)
                if on_boundary is not None:
                    callback_result = on_boundary(event)
                    if inspect.isawaitable(callback_result):
                        await callback_result
            # vLLM can coalesce DELTA callbacks at high concurrency. Count the
            # actual per-chunk stop tokens instead of assuming one callback is
            # one audio chunk, otherwise boundary timestamps drift earlier.
            if token_id in chunk_end_ids:
                chunk_index += 1
        return events, chunk_index

    async def _reset_mm_cache(self) -> bool:
        """Reset the engine's multimodal cache; tolerates sync or async engines."""
        reset_method = getattr(self.engine, "reset_mm_cache", None)
        if reset_method is None:
            raise RuntimeError("reset_mm_cache_on_eou=True but engine has no reset_mm_cache()")
        reset_result = reset_method()
        if inspect.isawaitable(reset_result):
            await reset_result
        return True

    async def _close_request_after_eou(
        self,
        request_id: str,
        *,
        reset_mm_cache_on_eou: bool | None = None,
    ) -> tuple[bool, bool]:
        """Abort the session at EOU; return ``(aborted, mm_cache_reset)``."""
        if not self.close_on_eou:
            return False, False
        abort_result = self.engine.abort(request_id)
        if inspect.isawaitable(abort_result):
            await abort_result
        reset = False
        should_reset = self.reset_mm_cache_on_eou if reset_mm_cache_on_eou is None else reset_mm_cache_on_eou
        if should_reset:
            reset = await self._reset_mm_cache()
        return True, reset

    async def _run_session_with_events(
        self,
        chunks: list[Any],
        request_id: str,
        throttle: bool,
        on_boundary: BoundaryCallback | None = None,
        reset_mm_cache_on_eou: bool | None = None,
    ) -> _SessionRunResult:
        """Run one session and observe SOU/EOU in the raw DELTA stream."""
        blank_id, eos_id = self.markers.blank_token_id, self.markers.eos_id
        flat: list[int] = []
        events: list[StreamingBoundaryEvent] = []
        chunk_index = 0

        async def record_delta(delta: list[int]) -> tuple[list[int], bool]:
            nonlocal chunk_index
            # The utterance is complete at the first EOU: keep that token and drop
            # anything the engine already produced after it in the same DELTA.
            ended = self.markers.eou_id is not None and self.markers.eou_id in delta
            if ended and self.close_on_eou:
                delta = delta[: delta.index(self.markers.eou_id) + 1]
            new_events, chunk_index = await self._emit_boundary_events(
                delta,
                token_offset=len(flat),
                chunk_index=chunk_index,
                on_boundary=on_boundary,
            )
            events.extend(new_events)
            flat.extend(delta)
            return delta, ended

        if throttle:
            done: asyncio.Queue = asyncio.Queue()

            async def gen_throttled():
                for i in range(len(chunks)):
                    yield self._stream_input(chunks, i)
                    await done.get()

            cur: list[int] = []
            completed_chunks = 0
            async for out in self.engine.generate(gen_throttled(), self._chunk_sp, request_id=request_id):
                d = out.outputs[0]
                delta, ended_by_eou = await record_delta(list(d.token_ids))
                cur.extend(delta)
                if ended_by_eou and self.close_on_eou:
                    aborted, reset = await self._close_request_after_eou(
                        request_id,
                        reset_mm_cache_on_eou=reset_mm_cache_on_eou,
                    )
                    return _SessionRunResult(flat, events, True, aborted, reset)
                if d.finish_reason is not None or (cur and cur[-1] in (blank_id, eos_id)):
                    cur = []
                    completed_chunks += 1
                    await done.put(1)
                if completed_chunks >= len(chunks):
                    break
            return _SessionRunResult(flat, events)

        async def gen_throughput():
            for i in range(len(chunks)):
                yield self._stream_input(chunks, i)

        async for out in self.engine.generate(gen_throughput(), self._chunk_sp, request_id=request_id):
            delta, ended_by_eou = await record_delta(list(out.outputs[0].token_ids))
            if ended_by_eou and self.close_on_eou:
                aborted, reset = await self._close_request_after_eou(
                    request_id,
                    reset_mm_cache_on_eou=reset_mm_cache_on_eou,
                )
                return _SessionRunResult(flat, events, True, aborted, reset)
            if out.finished:
                break
        return _SessionRunResult(flat, events)

    async def _run_session(self, chunks: list[Any], request_id: str, throttle: bool) -> list[int]:
        """Run one utterance's session and return only the flat generated token IDs."""
        if not self.markers.has_boundaries:
            return await self._run_session_transcript_only(chunks, request_id, throttle)
        result = await self._run_session_with_events(chunks, request_id, throttle)
        return result.token_ids

    def decode(self, token_ids: list[int]) -> str:
        """Decode generated token IDs to text, splitting on the chunk separator.

        Mirrors NeMo ``decode_with_blank``: the segment separator is the blank
        token for has_blank checkpoints, else EOS for noblank ones. Each segment
        is decoded independently (to preserve BPE within a turn) and the segments
        are joined with single spaces -- so per-chunk outputs are space-joined,
        not BPE-merged into one run. For has_blank, EOS is the turn-end and is
        dropped (not a boundary); for noblank, EOS *is* the boundary. SOU/EOU
        tokens are turn-boundary signals, never transcript text, so they are
        dropped as well.
        """
        eos_id = self.markers.eos_id
        sep_id = self.markers.blank_token_id if self.markers.has_blank else eos_id
        boundary_ids = {t for t in (self.markers.sou_id, self.markers.eou_id) if t is not None}
        segments: list[str] = []
        current: list[int] = []
        for t in token_ids:
            if t == sep_id:
                if current:
                    segments.append(self.tokenizer.decode(current, skip_special_tokens=True))
                    current = []
            elif self.markers.has_blank and t == eos_id:
                continue
            elif t in boundary_ids:
                continue
            else:
                current.append(t)
        if current:
            segments.append(self.tokenizer.decode(current, skip_special_tokens=True))
        return re.sub(r"\s+", " ", " ".join(s for s in segments if s)).strip()

    async def transcribe_with_events(
        self,
        chunks: list[Any],
        request_id: str,
        *,
        throttle: bool = False,
        on_boundary: BoundaryCallback | None = None,
        _reset_mm_cache_on_eou: bool | None = None,
    ) -> StreamingTranscriptionResult:
        """Transcribe one utterance and report its raw SOU/EOU boundary events.

        Args:
            chunks: Per-chunk embedding tensors ``(chunk_size, hidden)``.
            request_id: Unique vLLM request/session id for this utterance.
            throttle: If True, gate one chunk in flight at a time (debug mode).
            on_boundary: Optional sync or async callback invoked per boundary
                event as it is observed.
            _reset_mm_cache_on_eou: Internal override letting a concurrent batch
                defer the (global) multimodal cache reset to the end of the batch.

        Returns:
            A :class:`StreamingTranscriptionResult`. For checkpoints without
            SOU/EOU it carries the transcript with no boundary events.
        """
        if self.markers.has_boundaries:
            run = await self._run_session_with_events(
                chunks,
                request_id,
                throttle,
                on_boundary,
                reset_mm_cache_on_eou=_reset_mm_cache_on_eou,
            )
        else:
            run = _SessionRunResult(await self._run_session_transcript_only(chunks, request_id, throttle), [])
        return StreamingTranscriptionResult(
            text=self.decode(run.token_ids),
            token_ids=run.token_ids,
            boundary_events=run.boundary_events,
            ended_by_eou=run.ended_by_eou,
            request_aborted=run.request_aborted,
            mm_cache_reset=run.mm_cache_reset,
        )

    async def transcribe(self, chunks: list[Any], request_id: str, *, throttle: bool = False) -> str:
        """Transcribe one utterance from its list of per-chunk embedding tensors.

        Args:
            chunks: Per-chunk embedding tensors ``(chunk_size, hidden)`` from
                :func:`stream_encode`.
            request_id: Unique vLLM request/session id for this utterance.
            throttle: If True, gate one chunk in flight at a time (debug mode).

        Returns:
            The decoded transcript string.
        """
        result = await self.transcribe_with_events(chunks, request_id, throttle=throttle)
        return result.text

    async def transcribe_many_with_events(
        self,
        chunk_lists: list[list[Any]],
        *,
        tag: str = "streaming_stt",
        concurrency: int = 32,
        throttle: bool = False,
        on_boundary: BoundaryCallback | None = None,
    ) -> list[StreamingTranscriptionResult]:
        """Boundary-aware equivalent of :meth:`transcribe_many`.

        ``reset_mm_cache()`` is engine-global: firing it while sibling sessions
        are still decoding would drop their cached audio embeddings. So when the
        batch would reset, the per-session resets are suppressed and one reset is
        issued after every session in the batch has finished.
        """
        semaphore = asyncio.Semaphore(concurrency)
        defer_mm_cache_reset = self.markers.has_boundaries and self.close_on_eou and self.reset_mm_cache_on_eou

        async def _bounded(i: int) -> StreamingTranscriptionResult:
            async with semaphore:
                return await self.transcribe_with_events(
                    chunk_lists[i],
                    f"{tag}_{i}",
                    throttle=throttle,
                    on_boundary=on_boundary,
                    _reset_mm_cache_on_eou=False if defer_mm_cache_reset else None,
                )

        results = await asyncio.gather(*[_bounded(i) for i in range(len(chunk_lists))])
        if defer_mm_cache_reset and any(result.ended_by_eou for result in results):
            await self._reset_mm_cache()
            results = [replace(r, mm_cache_reset=True) if r.ended_by_eou else r for r in results]
        return results

    async def transcribe_many(
        self,
        chunk_lists: list[list[Any]],
        *,
        tag: str = "streaming_stt",
        concurrency: int = 32,
        throttle: bool = False,
    ) -> list[str]:
        """Transcribe many utterances concurrently (one vLLM session each).

        Args:
            chunk_lists: Per-utterance lists of per-chunk embedding tensors.
            tag: Request-id prefix; each utterance gets ``f"{tag}_{i}"``.
            concurrency: Max concurrent sessions (continuous batching across them).
            throttle: Per-chunk gating (debug mode).

        Returns:
            Transcripts aligned to ``chunk_lists`` order.
        """
        if not self.markers.has_boundaries:
            sem = asyncio.Semaphore(concurrency)

            async def _bounded(i: int) -> str:
                async with sem:
                    return await self.transcribe(chunk_lists[i], f"{tag}_{i}", throttle=throttle)

            return await asyncio.gather(*[_bounded(i) for i in range(len(chunk_lists))])

        results = await self.transcribe_many_with_events(
            chunk_lists,
            tag=tag,
            concurrency=concurrency,
            throttle=throttle,
        )
        return [result.text for result in results]
